from mystructures.stacks.statictypestack.StaticTypeStack import StaticTypeStack
from mystructures.linkedlist.circularlinkedlist.CircularLinkedList import CircularLinkedList
from mystructures.hashtable.SeparateChainingHashtable import SeparateChainingHashtable